import { Box, Button } from "@chakra-ui/react";
import { usePageState } from "@src/shared/state";
import { useWallet } from "@src/shared/walletV1";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  const wallet = useWallet();
  const [state, methods] = usePageState();
  const handleFollowClick = async () => {
    if (!state.currentAddress) {
      methods.openConnectToWallet();
    }
    // const res = await wallet.followProfile();
    const res = await wallet.followProfileForFree();
    //ask for connect
    //effect -> call method
  };
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Button onClick={handleFollowClick}>Follow</Button>
    </Box>
  );
}
